local HudController = require(script.Parent.Controllers.HudController)
local InventoryController = require(script.Parent.Controllers.InventoryController)
local ShipControls = require(script.Parent.Controllers.ShipControls)
local StaminaController = require(script.Parent.Controllers.StaminaController)

HudController.Start()
InventoryController.Start()
ShipControls.Start()
StaminaController.Start()
